import { COLORS, FONTS } from './constants';

export const S = {
  container: {
    padding: "20px 28px",
    maxWidth: 1440,
    margin: "0 auto",
    fontFamily: FONTS.mono,
    color: COLORS.text.primary,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "1.5px",
    color: COLORS.text.dim,
    marginBottom: 10,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  divider: { flex: 1, height: 1, background: COLORS.border.primary },
  card: {
    background: COLORS.bg.elevated,
    border: `1px solid ${COLORS.border.primary}`,
    borderRadius: 6,
    overflow: "hidden",
  },
  summaryRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(155px, 1fr))",
    gap: 10,
    marginBottom: 20,
  },
  summaryCard: {
    padding: "12px 16px",
    background: COLORS.bg.elevated,
    border: `1px solid ${COLORS.border.primary}`,
    borderRadius: 6,
  },
  cardLabel: {
    fontSize: 9,
    fontFamily: FONTS.ui,
    color: COLORS.text.dim,
    textTransform: "uppercase",
    letterSpacing: "0.8px",
    fontWeight: 500,
  },
  cardValue: {
    fontSize: 17,
    fontWeight: 600,
    fontFamily: FONTS.mono,
    marginTop: 4,
    color: COLORS.text.primary,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 11,
    fontVariantNumeric: "tabular-nums",
  },
  th: {
    padding: "8px 12px",
    textAlign: "left",
    fontSize: 9,
    fontFamily: FONTS.ui,
    fontWeight: 600,
    color: COLORS.text.dim,
    textTransform: "uppercase",
    letterSpacing: "0.8px",
    borderBottom: `1px solid ${COLORS.border.secondary}`,
    background: COLORS.bg.secondary,
    position: "sticky",
    top: 0,
  },
  thRight: {
    padding: "8px 12px",
    textAlign: "right",
    fontSize: 9,
    fontFamily: FONTS.ui,
    fontWeight: 600,
    color: COLORS.text.dim,
    textTransform: "uppercase",
    letterSpacing: "0.8px",
    borderBottom: `1px solid ${COLORS.border.secondary}`,
    background: COLORS.bg.secondary,
    position: "sticky",
    top: 0,
  },
  td: {
    padding: "8px 12px",
    borderBottom: `1px solid ${COLORS.border.primary}`,
    color: COLORS.text.secondary,
    fontFamily: FONTS.mono,
  },
  tdRight: {
    padding: "8px 12px",
    borderBottom: `1px solid ${COLORS.border.primary}`,
    color: COLORS.text.secondary,
    fontFamily: FONTS.mono,
    textAlign: "right",
  },
  btn: {
    padding: "4px 10px",
    fontSize: 10,
    fontFamily: FONTS.mono,
    cursor: "pointer",
    borderRadius: 4,
    border: `1px solid ${COLORS.border.secondary}`,
    background: "transparent",
    color: COLORS.text.muted,
    transition: "all 0.12s",
  },
  btnPrimary: {
    padding: "4px 10px",
    fontSize: 10,
    fontFamily: FONTS.mono,
    cursor: "pointer",
    borderRadius: 4,
    border: `1px solid ${COLORS.accent.blueBorder}`,
    background: COLORS.accent.blueBg,
    color: COLORS.accent.blue,
  },
  btnDanger: {
    padding: "3px 8px",
    fontSize: 9,
    fontFamily: FONTS.mono,
    cursor: "pointer",
    borderRadius: 3,
    border: `1px solid ${COLORS.border.secondary}`,
    background: "transparent",
    color: COLORS.text.dim,
    transition: "all 0.12s",
  },
  btnSuccess: {
    padding: "3px 8px",
    fontSize: 9,
    fontFamily: FONTS.mono,
    cursor: "pointer",
    borderRadius: 3,
    border: `1px solid ${COLORS.border.secondary}`,
    background: "transparent",
    color: COLORS.text.muted,
    transition: "all 0.12s",
  },
  input: {
    background: COLORS.bg.input,
    border: `1px solid ${COLORS.border.secondary}`,
    color: COLORS.text.primary,
    padding: "5px 8px",
    borderRadius: 4,
    fontFamily: FONTS.mono,
    fontSize: 11,
    outline: "none",
    width: 100,
  },
  subtotalRow: {
    padding: "8px 12px",
    background: COLORS.bg.primary,
    borderTop: `1px solid ${COLORS.border.secondary}`,
    display: "flex",
    justifyContent: "space-between",
    fontSize: 10,
    fontWeight: 600,
    fontFamily: FONTS.mono,
  },
  badge: (color) => ({
    display: "inline-block",
    padding: "1px 6px",
    borderRadius: 3,
    fontSize: 8,
    fontWeight: 600,
    fontFamily: FONTS.mono,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    background: color + "18",
    color: color,
    border: `1px solid ${color}30`,
  }),
  tooltip: {
    background: COLORS.bg.elevated,
    border: `1px solid ${COLORS.border.secondary}`,
    borderRadius: 6,
    padding: "8px 12px",
    fontSize: 10,
    fontFamily: FONTS.mono,
  },
};

export const pnlColor = (v) => v >= 0 ? COLORS.positive.text : COLORS.negative.text;
export const blurStyle = { filter: "blur(8px)", userSelect: "none", transition: "filter 0.2s" };
